<?php
/**
 * @file
 * Custom functionality for a wind farm database.
 */

/**
 * Implements hook_help().
 */
function windfarms_help($path, $arg) {
  switch ($path) {
    case 'admin/help#windfarms':{
      $ret_val = '<h3>' . t('About') . '</h3>';
      $ret_val = '<p>' . t('The Wind Farms module makes it easy to manage a database of wind farms.') . '</p>';
      return $ret_val;
      break;
    }
  }
}

/**
 * Implements hook_permission().
 */
function windfarms_permission() {
  return array(
    'administer wind farms' => array(
      'title' => t('Administer Wind Farms'),
      'description' => t('Perform administrative tasks on Wind Farms functionality'),
    ),
  );
}
