<?php
/**
 * @file
 * Wind Farms installation
 */

/**
 * Implements hook_install().
 */
function windfarms_install() {
  // Set default variables.
  variable_set('windfarms_gmap', 1);
  variable_set('windfarms_default_center_lat', 42.91455);
  variable_set('windfarms_default_center_long', -75.569851);
  variable_set('windfarms_default_gmap_zoom', 8);

  // Get localization function for installation as t() may be unavailable.
  $t = get_t();

  // Give user feedback.
  drupal_set_message($t('Wind Farms variables created.'));

  // Content type definition.
  $content_type = array(
    'type' => 'windfarm',
    'name' => $t('Wind Farm'),
    'description' => $t('A Wind Farm, including location.'),
    'title_label' => $t('Facility Name'),
    'base' => 'node_content',
    'custom' => TRUE,
  );

  // Set remaining definitions with defaults.
  $node_type = node_type_set_defaults($content_type);

  // Save the content type.
  node_type_save($node_type);
}

/**
 * Implements hook_uninstall().
 */
function windfarms_uninstall() {
  // Delete variables.
  variable_del('windfarms_gmap');
  variable_del('windfarms_default_center_lat');
  variable_del('windfarms_default_center_long');
  variable_del('windfarms_default_gmap_zoom');

  // Inform the user of the removal.
  $t = get_t();
  drupal_set_message($t('Wind Farms variables removed.'));
}